# Generated by Django 6.0.4 on 2026-04-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['full_name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-delivery_date'], 'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='orderitemmaterial',
            options={'verbose_name': 'Order Item Material', 'verbose_name_plural': 'Order Item Materials'},
        ),
        migrations.AlterModelOptions(
            name='productionstage',
            options={'ordering': ['started_at'], 'verbose_name': 'Production Stage', 'verbose_name_plural': 'Production Stages'},
        ),
        migrations.AlterModelOptions(
            name='workticket',
            options={'ordering': ['-priority', 'deadline'], 'verbose_name': 'Work Ticket', 'verbose_name_plural': 'Work Tickets'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
