# Generated by Django 6.0.4 on 2026-05-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_catalogue_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
