# Generated by Django 6.0.4 on 2026-05-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_customer_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('garment_types', models.JSONField(default=list)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_hint', models.CharField(blank=True, max_length=200)),
                ('requires_measurements', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catalogue Item',
                'verbose_name_plural': 'Catalogue Items',
                'db_table': 'catalogue_item',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.employee'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_fabric',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='catalogue_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.catalogueitem'),
        ),
        migrations.CreateModel(
            name='OrderItemMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bust', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sleeve', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('inseam', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('neck', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='item_measurements', to='shop.customer')),
                ('order_item', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='shop.orderitem')),
            ],
            options={
                'verbose_name': 'Order Item Measurement',
                'verbose_name_plural': 'Order Item Measurements',
                'db_table': 'order_item_measurement',
                'ordering': ['-created_at'],
            },
        ),
    ]
