# Generated by Django 6.0.4 on 2026-05-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_catalogueitem_orderitem_assigned_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alert when stock drops below this quantity.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid as deposit at time of order.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('deposit', 'Deposit Paid'), ('paid', 'Fully Paid')], default='unpaid', max_length=20),
        ),
    ]
