# Generated by Django 6.0.4 on 2026-05-08 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_payment_fields_material_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('order_status', 'Order status'), ('payment_status', 'Payment status'), ('order_item_status', 'Line item status'), ('order_item_assigned', 'Line item assignment'), ('ticket_status', 'Work ticket status'), ('ticket_assigned', 'Work ticket assignment'), ('stage_started', 'Stage started'), ('stage_completed', 'Stage finished'), ('delivery', 'Delivery')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='shop.order')),
            ],
            options={
                'verbose_name': 'Production log',
                'verbose_name_plural': 'Production logs',
                'db_table': 'order_production_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
