# Generated by Django 6.0.4 on 2026-05-08 14:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def migrate_legacy_deposits(apps, schema_editor):
    Order = apps.get_model("shop", "Order")
    OrderPayment = apps.get_model("shop", "OrderPayment")
    legacy = tuple(
        Order.objects.filter(deposit_paid__gt=Decimal("0"))
        .exclude(deposit_paid__isnull=True)
        .values_list("pk", "deposit_paid")
    )
    if not legacy:
        return
    OrderPayment.objects.bulk_create(
        [
            OrderPayment(
                order_id=pk,
                amount=amt,
                method="other",
                notes="Imported from legacy cumulative deposit.",
            )
            for pk, amt in legacy
        ]
    )


def reverse_noop(apps, schema_editor):
    OrderPayment = apps.get_model("shop", "OrderPayment")
    OrderPayment.objects.filter(notes="Imported from legacy cumulative deposit.").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_order_production_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("transfer", "Bank transfer"),
                            ("other", "Other"),
                            ("admin_mark_delivered", "Marked delivered (admin)"),
                        ],
                        default="cash",
                        max_length=32,
                    ),
                ),
                ("recorded_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="shop.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "order_payment",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.RunPython(migrate_legacy_deposits, reverse_noop),
    ]
